- name: Install APT packages
  hosts: localhost
  connection: local 
  become: yes
  tasks:
    - name: Install apt packages
      apt:
        update_cache: yes
        name:
          - vim
          - curl
          - git
          - tmux
          - htop
          - open-vm-tools-desktop
        state: latest

- name: Run custom roles
  hosts: localhost
  connection: local
  roles:
    - configure-bash
    - install-chrome
    - install-python-from-source
    - install-pip
    - install-vscode
    - install-wireshark
  
- name: Run galaxy roles
  hosts: localhost
  connection: local
  become: yes
  roles:
    - geerlingguy.docker

- name: Install Snap and Snap packages
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install snapd
      apt:
        update_cache: yes
        name: snapd
        state: latest

    - name: Install Snap packages
      community.general.snap:
        name:
          - pycharm-community
          - intellij-idea-community
          - postman
        classic: yes
        state: present

- name: Configure GUI
  hosts: localhost
  connection: local
  tasks:
    - name: Set automatic blank screen to never
      shell: gsettings set org.gnome.desktop.session idle-delay 0

    - name: Set favorites
      shell: >
        gsettings set org.gnome.shell favorite-apps 
        "['google-chrome.desktop', 'firefox.desktop', 
        'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 
        'code.desktop', 'postman_postman.desktop', 
        'intellij-idea-community_intellij-idea-community.desktop', 
        'pycharm-community_pycharm-community.desktop', 'wireshark.desktop']"

- name: Set vimrc
  hosts: localhost
  connection: local
  tasks:
    - name: Set vimrc
      get_url:
        url: https://raw.githubusercontent.com/syth3/Configs/master/vimrc
        dest: "/home/{{ username }}/.vimrc"
        mode: '0766'

- name: Finishing touches and clean up
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update, upgrade, and autoremove all apt packages
      apt:
        update_cache: yes
        autoremove: yes
        upgrade: yes

    - name: Reboot system
      reboot:

